### ISSUE TITLE
tf.py_func() error

### ISSUE THREAD

**Issue by justinsherman** [TensorBox/TensorBox#218]
I have configured TensorBox on my 64-bit GPU running Ubuntu 14.04. TensorFlow is set up on the machine and is completely functional.

When I run
`python train.py --hypes hypes/lstm_rezoom.json --gpu 0 --logdir output`
within the TensorBox directory - which should begin retraining the network on the specified directory of data - I receive generate an error on lines 400-405 of train.py:

```
pred_log_img = tf.py_func(log_image,
                                      [test_image, test_pred_confidences, test_pred_boxes, global_step, 'pred'],
                                      [tf.float32])
true_log_img = tf.py_func(log_image,
                                      [test_image, test_true_confidences, test_true_boxes, global_step, 'true'],
                                      [tf.float32])
```
The `py_func` function is returning a tensor of 'unknown shape', which in turn yields an error. I run this very same bit of code on my CPU and do not receive any errors.

How do I fix these lines to extract the tensor without having an unknown shape?

**Comment by RomanSteinberg** [comment]
@justinsherman Can you print the exact error log? Can you print shapes of input parameters before `py_func` call?

**Comment by justinsherman** [comment]
Printing the tensors (computed by the two `py_func` operations yields:
`[<tf.Tensor 'PyFunc:0' shape=<unknown> dtype=float32>]
[<tf.Tensor 'PyFunc_2:0' shape=<unknown> dtype=float32>]`


And the error log is as follows:
`Traceback (most recent call last):
  File "~/.local/lib/python2.7/site-packages/tensorflow/python/ops/script_ops.py", line 85, in __call__
    ret = func(*args)
  File "train.py", line 387, in log_image
    rnn_len=H['rnn_len'])[0]
  File "~/tensorbox/utils/train_utils.py", line 127, in add_rectangles
    from stitch_wrapper import stitch_rects
ImportError: ~/tensorbox/utils/stitch_wrapper.so: undefined symbol: PyUnicodeUCS2_DecodeUTF8
W tensorflow/core/framework/op_kernel.cc:975] Internal: Failed to run py callback pyfunc_3: see error log.
W tensorflow/core/framework/op_kernel.cc:975] Internal: Failed to run py callback pyfunc_3: see error log.
         [[Node: PyFunc_3 = PyFunc[Tin=[DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_INT32, DT_STRING], Tout=[DT_FLOAT], token="pyfunc_3", _device="/job:localhost/replica:0/task:0/cpu:0"](fifo_queue_1_DequeueMany, strided_slice_12, strided_slice_13, Variable/read, PyFunc_3/input_4)]]
W tensorflow/core/framework/op_kernel.cc:975] Internal: Failed to run py callback pyfunc_3: see error log.
         [[Node: PyFunc_3 = PyFunc[Tin=[DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_INT32, DT_STRING], Tout=[DT_FLOAT], token="pyfunc_3", _device="/job:localhost/replica:0/task:0/cpu:0"](fifo_queue_1_DequeueMany, strided_slice_12, strided_slice_13, Variable/read, PyFunc_3/input_4)]]
Traceback (most recent call last):
  File "~/.local/lib/python2.7/site-packages/tensorflow/python/ops/script_ops.py", line 85, in __call__
    ret = func(*args)
  File "train.py", line 387, in log_image
    rnn_len=H['rnn_len'])[0]
  File "~/tensorbox/utils/train_utils.py", line 127, in add_rectangles
    from stitch_wrapper import stitch_rects
ImportError: ~/tensorbox/utils/stitch_wrapper.so: undefined symbol: PyUnicodeUCS2_DecodeUTF8
W tensorflow/core/framework/op_kernel.cc:975] Internal: Failed to run py callback pyfunc_1: see error log.
W tensorflow/core/kernels/queue_base.cc:294] _0_fifo_queue: Skipping cancelled enqueue attempt with queue not closed
W tensorflow/core/kernels/queue_base.cc:294] _1_fifo_queue_1: Skipping cancelled enqueue attempt with queue not closed
Traceback (most recent call last):
  File "train.py", line 552, in <module>
    main()
  File "train.py", line 549, in main
    train(H, test_images=[])
  File "train.py", line 507, in train
    ], feed_dict=lr_feed)
  File "~/.local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 766, in run
    run_metadata_ptr)
  File "~/.local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 964, in _run
    feed_dict_string, options, run_metadata)
  File "~/.local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1014, in _do_run
    target_list, options, run_metadata)
  File "~/.local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1034, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InternalError: Failed to run py callback pyfunc_3: see error log.
         [[Node: PyFunc_3 = PyFunc[Tin=[DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_INT32, DT_STRING], Tout=[DT_FLOAT], token="pyfunc_3", _device="/job:localhost/replica:0/task:0/cpu:0"](fifo_queue_1_DequeueMany, strided_slice_12, strided_slice_13, Variable/read, PyFunc_3/input_4)]]

Caused by op u'PyFunc_3', defined at:
  File "train.py", line 552, in <module>
    main()
  File "train.py", line 549, in main
    train(H, test_images=[])
  File "train.py", line 451, in train
    smooth_op, global_step, learning_rate) = build(H, q)
  File "train.py", line 405, in build
    [tf.float32])
  File "~/.local/lib/python2.7/site-packages/tensorflow/python/ops/script_ops.py", line 192, in py_func
    input=inp, token=token, Tout=Tout, name=name)
  File "~/.local/lib/python2.7/site-packages/tensorflow/python/ops/gen_script_ops.py", line 40, in _py_func
    name=name)
  File "~/.local/lib/python2.7/site-packages/tensorflow/python/framework/op_def_library.py", line 759, in apply_op
    op_def=op_def)
  File "~/.local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 2240, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "~/.local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1128, in __init__
    self._traceback = _extract_stack()

InternalError (see above for traceback): Failed to run py callback pyfunc_3: see error log.
         [[Node: PyFunc_3 = PyFunc[Tin=[DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_INT32, DT_STRING], Tout=[DT_FLOAT], token="pyfunc_3", _device="/job:localhost/replica:0/task:0/cpu:0"](fifo_queue_1_DequeueMany, strided_slice_12, strided_slice_13, Variable/read, PyFunc_3/input_4)]]
`

**Comment by RomanSteinberg** [comment]
@justinsherman Did you run `make` and `make hungarian`? 

Also I suggest to use docker for TF.

**Comment by justinsherman** [comment]
@RomanSteinberg Yes, I ran both `make` commands. What do you mean by control the output?

**Comment by RomanSteinberg** [comment]
@justinsherman I mean that you should look for succes or fail of this commands.

**Comment by RomanSteinberg** [comment]
Now I think you have to concentrate your attention at the following error message:
```
ImportError: /home/tensorbox/utils/stitch_wrapper.so: undefined symbol: PyUnicodeUCS2_DecodeUTF8
```
Firstly, It is first error, which means that others could be caused by wrong program behavior after this error. Secondly, it is a linker problem, so I think the problem caused by incorrect `stitch_wrapper.so` building.

So, delete this file `stitch_wrapper.so`. Run make again. Look at the make console messages. If there an error, post it here or try to resolve it yourself. If no error happen, run train again and write a message if it succeed or failed.

**Comment by justinsherman** [comment]
@RomanSteinberg I received the following error when running 'make':

`pip install runcython
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 635, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 943, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 834, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.VersionConflict: (pip 8.1.1 (/usr/lib/python3/dist-packages), Requirement.parse('pip==7.0.0'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/pip", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2927, in <module>
    @_call_aside
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2913, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2940, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 637, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 650, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 829, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'pip==7.0.0' distribution was not found and is required by the application
Makefile:5: recipe for target 'all' failed
make: *** [all] Error 1
`

I have to check my pip installation.

**Comment by justinsherman** [comment]
@RomanSteinberg Rebuilding the make seems to have alleviated the py_func error, but I am now running into this:

```Traceback (most recent call last):
  File "train.py", line 552, in <module>
    main()
  File "train.py", line 549, in main
    train(H, test_images=[])
  File "train.py", line 464, in train
    d = gen.next()
  File "/usr/project/xtmp/js684/tensorbox/utils/train_utils.py", line 83, in load_data_gen
    for d in data:
  File "/usr/project/xtmp/js684/tensorbox/utils/train_utils.py", line 32, in load_idl_tf
    annolist = al.parse(idlfile)
  File "/usr/project/xtmp/js684/tensorbox/utils/annolist/AnnotationLib.py", line 750, in parse
    name, ext = os.path.splitext(filename)
  File "/usr/lib/python2.7/posixpath.py", line 98, in splitext
    return genericpath._splitext(p, sep, altsep, extsep)
  File "/usr/lib/python2.7/genericpath.py", line 99, in _splitext
    sepIndex = p.rfind(sep)
AttributeError: 'bool' object has no attribute 'rfind'
```

**Comment by RomanSteinberg** [comment]
@justinsherman it is kind of side effect error I think. Print value of `filename` variable before line 750 in AnnotationLib.py. Then check the path to file. If it seems ok use the following code
```
print (os.path.exists(filename))
```
It will explain a lot.

**Comment by justinsherman** [comment]
@RomanSteinberg The OS path exists; the problem is the value of `filename` is somehow being set to `False`. I've looked into it and I can't seem to trace the error. The code is cloned directly from the Git repo, so do you have any idea what the cause of that might be?

**Comment by justinsherman** [comment]
RESOLVED: The issue was with an outdated package build in the python2.7 folder. Solution is therefore to check that all packages are up to date / the correct version before building (`cd utils && make`) and training the network.
